from . import equipment
from . import repair_order
from . import repair_order_line
from . import repair_diagnosis
from . import repair_diagnosis_line
from . import procurement_group
from . import stock_move
from . import stock_rule
from . import stock_picking
from . import account_move_line
from . import account_analytic_line
from . import product_template
from . import maintenance_plan
from . import maintenance_plan_type
from . import repair_order_tag
from . import res_partner
from . import equipment_category
from . import warranty_ticket