# -*- coding: utf-8 -*-

{
    'name': 'Minh Duong Store Configurations',
    'description': '''
    Module for Minh Duong Store Configurations
    ''',
    'author': 'VietTotal',
    'application': True,
    'category': 'Configurations',
    "license": "LGPL-3",
    'depends': [
        'base',
        'web',
        'stock',
        'product_expiry',
        'stock_picking_batch',
        'stock_packaging_calculator',
        'vtt_product_expiry_by_percentage',
        'vtt_inventory_report',
        'fleet',
        # 'vtt_inventory_mbs',
        'report_py3o',
        'web_widget_numeric_step',
        'datetime_formatter',
        'project',
        'contacts',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'data': [
        'security/ir.model.access.csv',
        # 'security/minhduong_security.xml',
        'data/product_template_default_datas.xml',
        'data/config_parameter_data.xml',
        'data/document_datas.xml',
        'data/default_utility_datas.xml',
        'data/project_task_datas.xml',
        'views/stock_picking_views.xml',
        'views/stock_production_lot_view.xml',
        'views/stock_picking_type_views.xml',
        'views/stock_location_views.xml',
        'views/stock_picking_batch_views.xml',
        'views/product_views.xml',
        'views/stock_quant_views.xml',
        'views/stock_move_views.xml',
        'views/partner_views.xml',
        'views/fleet_vehicle_log_views.xml',
        'views/ir_attachment_views.xml',
        'views/product_tag_views.xml',
        'report/report_delivery.xml',
        'report/report_barcode_print.xml',
        'report/stock_picking_product_import_report.xml',
        'report/product_label_templates.xml',
        'report/stock_traceability_report.xml',
        'wizard/stock_custom_import_wz_views.xml',
        'wizard/stock_location_gen_wz_views.xml',
        'wizard/product_update_wz_views.xml',
        'wizard/partner_update_wz_views.xml',
        'wizard/fleet_update_wz_views.xml',
        'wizard/fleet_log_service_import_wz_views.xml',
        'wizard/stock_move_line_gen_wz_views.xml',
        # 'wizard/product_lot_print_wz_views.xml',
        'wizard/stock_picking_move_import_wz_views.xml',
        'wizard/product_label_layout_views.xml',
        'wizard/barcode_scan_wz_views.xml',
        'wizard/stock_move_line_split_wz_views.xml',
        'wizard/stock_internal_transfer_wz_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'vtt_minhduong_config/static/src/js/user_menu_items.js',
            'vtt_minhduong_config/static/src/js/field_instant_change_widget.js',
        ],
    },
}