# -*- coding: utf-8 -*-

{
    'name': 'Cemetery Manager by VietTotal',
    'description': '''
    Cemetery and funeral business manager by VietTotal
    ''',
    'application': True,
    'depends': [
        'sale_management',
        'vtt_sale_subscription',
        'vtt_board_department',
        'hr',
        'project',
        'vtt_custom_rating_hr',
        'vtt_approvals',
        'vtt_web_dashboard',
        # 'web_dashboard',
        'contacts',
        'event',
        'calendar',
        'event',
        'web_domain_field',
        'base_automation',
    ],
    'data': [
        'security/cemetery_security.xml',
        'security/ir.model.access.csv',
        'data/config_data.xml',
        'data/construct_stage_data.xml',
        'data/approval_category_data.xml',
        'data/custom_rating_stage_data.xml',
        'data/mail_templates.xml',
        'data/default_channel_data.xml',
        'data/default_automation_data.xml',
        'data/cron_data.xml',
        'views/land_plot_views.xml',
        'views/land_tomb_views.xml',
        'views/land_tomb_slot_views.xml',
        'views/land_contract_views.xml',
        'views/land_place_views.xml',
        'views/construct_views.xml',
        'views/construct_stage_views.xml',
        'views/customer_card_views.xml',
        'views/custom_rating_views.xml',
        'views/sale_order_views.xml',
        'views/sale_subscription_views.xml',
        'views/product_views.xml',
        'views/partner_views.xml',
        'views/project_task_views.xml',
        'views/approval_request_views.xml',
        'views/calendar_event_views.xml',
        'data/dashboard_data.xml',
        'views/event_event_views.xml',
        'views/hr_department_views.xml',
        'views/config_parameter_views.xml',
        'views/product_category_views.xml',
        'views/project_task_rating_views.xml',
        'views/lhv_menus.xml',
    ],
    'author': 'Evils'
}